### PR TITLE
Request merge of improvements accessibility (#5) and #4 functionality: email validation logic into main

### LINKED ISSUE #5: improvements: accessibility
Accessibility will be addressed, including, but not exclusive to:

1. Background-foreground contrast rations (to meet WCAG 2.1 AAA compliance standards)
2. Associated labels for form elements
3. Aria labels on icon links
4. Aria attributes on footer nav links (to discern from header links)

The possibility for E2E accessibility testing via Playwright may also be considered to highlight any additional improvements.

### PR DESCRIPTION
**Pull request by asbhogal**
I've decided to do a PR which combines changes made on this branch **and** the accessibility one (which was merged into this.) Afterward this has been merged into main, I can look into the responsive one. This way it keeps the branches on-topic whilst also preventing any conflicts or missing changes between the different ones.

**Changes made in this branch:**

- Amended aria-labels for icon links
- Changed semantics for form incl. attributes
- Added email label text which is visually hidden but accessible to screen readers
- Changed color for Fylo link to meet background-foreground standards (AAA)

**Changes made in email validation branch which were subsequently merged into this one:**

- Integrated three unit tests (using Vitest and JSDom) 
- Updated error message and styles to better match mockups

(see https://github.com/ofthewildfire/fem-fylo-landing-page/issues/4)

Ready to perform PR after your review ✨

### CODE REVIEW

**Comment by ofthewildfire** [comment]
A-okay! Testing is wild, my time was messed up.

**Comment by ofthewildfire** [comment]
Will delete branch  after confirmation.

**Comment by asbhogal** [comment]
**Wooop wooop.** No worries. Let me know when it's all 100% on your end and what I'll do here is switch to the main and trigger a redeployment on Vercel so the latest production has all the changes in. 🙏🏽

**Comment by asbhogal** [comment]
Main branch re-deployed successfully. (**woop**) Have deleted this branch (just need to delete it locally.)

**Comment by ofthewildfire** [comment]
Okie ✨✨ apparently this can be done via email so this message is just a
test tbh lmao 🤣

**Comment by asbhogal** [comment]
Lmao oh yeah I didn't know that - it also shows in the PR 😂 that's cool ✨ roger-roger🫡
________________________________

**Comment by asbhogal** [comment]
Lmao oh yeah I didn't know that - it also shows in the PR 😂 that's cool ✨ roger-out 🫡
________________________________

**Pull request merged**
